In [1]:
#DHZ 1951
import numpy as np 

arr = np.arange(0,20,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [2]:
#DHZ 1951
arr_flot = np.random.rand(4,3)
arr_flot

array([[0.01998537, 0.76849893, 0.59725165],
       [0.30297299, 0.98096206, 0.83721211],
       [0.72751508, 0.19649636, 0.47540177],
       [0.19272725, 0.32609529, 0.67693055]])

In [6]:
#DHZ 1951

arr_ent = np.random.randint(10, size=(2,3))
arr_ent

array([[4, 4, 0],
       [5, 3, 4]])

In [7]:
#DHZ 1951
arr_6 = np.full((3,3),6)
arr_6

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [8]:
#DHZ 1951
np.append(arr, [12, 13, 14, 51])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 12, 13, 14, 51])

In [9]:
#DHZ 1951
np.insert(arr,2, [42,34])

array([ 0,  2, 42, 34,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
#DHZ 1951
np.delete(arr_ent,1,axis=0)

array([[4, 4, 0]])