In [1]:
#DHZ 1951

import numpy as np
a = np.array([1, 2, 3], float)
b = np.array([0, 1, 1], float)

np.dot(b, a)

5.0

In [2]:
#DHZ 1951
a = np.array([[5,2], [4, 8]], float)
b = np.array([[2,4], [5, 3]], float)

print(a, "\n ***********")
print(b, "\n ***********")

[[5. 2.]
 [4. 8.]] 
 ***********
[[2. 4.]
 [5. 3.]] 
 ***********


In [3]:
a @ b

array([[20., 26.],
       [48., 40.]])

In [4]:
#DHZ 1951
a = np.array([[8, 5], [3, 4]])
print(a, "\n ***********")
np.linalg.det(a)

[[8 5]
 [3 4]] 
 ***********


17.0

In [5]:
#DHZ 1951
vals, vecs = np.linalg.eig(a)
print(vals, "\n ***********")
print(vecs, "\n ***********")

[10.35889894  1.64110106] 
 ***********
[[ 0.90440309 -0.61810602]
 [ 0.4266791   0.78609474]] 
 ***********


In [7]:
#DHZ 1951
import numpy as np

a = np.array([2, 4, 9], float)

In [12]:
np.exp(a)

array([7.38905610e+00, 5.45981500e+01, 8.10308393e+03])

In [13]:
#DHZ 1951
import numpy as np
arr = np.array([5,36,17,18,9])
arr_2 = np.array([8,24,17,19,9])

In [15]:
np.multiply(arr,arr_2)

array([ 40, 864, 289, 342,  81])