In [1]:
#DHZ 1951
import numpy as np 

In [3]:
arreglo = np.array([0,1,2,3,4,5])

In [4]:
arreglo, type(arreglo)

(array([0, 1, 2, 3, 4, 5]), numpy.ndarray)

In [5]:
notas = [16,17,14,17,19,15]

ar_notas = np.array(notas, dtype=float)

In [6]:
ar_notas, type(ar_notas[0])

(array([16., 17., 14., 17., 19., 15.]), numpy.float64)

In [7]:
ar_notas_todas = np.array(([0,1,2,3,4,5], notas))
ar_notas_todas

array([[ 0,  1,  2,  3,  4,  5],
       [16, 17, 14, 17, 19, 15]])

In [8]:
#DHZ 1951
print(ar_notas_todas.ndim)
print(ar_notas.ndim)

2
1


In [9]:
#DHZ 1951
print(ar_notas_todas.shape)
print(ar_notas.shape)

(2, 6)
(6,)


In [10]:
#DHZ 1951
arr = np.zeros((2,3), dtype=float)
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
#DHZ 1951 
ar2 = np.ones((3,4), dtype=float)
print(ar2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
ar4 = np.identity((4), dtype=float)
print(ar4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
ar5 = np.arange(1,9)
print(ar5)

[1 2 3 4 5 6 7 8]
