In [1]:
#DHZ 1951 
import numpy as np
arr_ent = np.random.randint(100, size=(3,4))
arr_ent

array([[72,  6, 30, 25],
       [90, 95, 60, 41],
       [67, 12, 41,  9]])

In [2]:
arr_ent.astype(float)

array([[72.,  6., 30., 25.],
       [90., 95., 60., 41.],
       [67., 12., 41.,  9.]])

In [3]:
#DHZ 1951
arr_ent

array([[72,  6, 30, 25],
       [90, 95, 60, 41],
       [67, 12, 41,  9]])

In [5]:
arr_ent.sort()
arr_ent

array([[ 6, 25, 30, 72],
       [41, 60, 90, 95],
       [ 9, 12, 41, 67]])

In [6]:
arr_ent.sort(axis=0)
arr_ent

array([[ 6, 12, 30, 67],
       [ 9, 25, 41, 72],
       [41, 60, 90, 95]])

In [7]:
#DHZ 1951
arr_ent

array([[ 6, 12, 30, 67],
       [ 9, 25, 41, 72],
       [41, 60, 90, 95]])

In [12]:
arr_ent = arr_ent.reshape(6,2)
arr_ent

array([[ 6, 12],
       [30, 67],
       [ 9, 25],
       [41, 72],
       [41, 60],
       [90, 95]])

In [14]:
#DHZ 1951
plano_arr = arr_ent.flatten()
print(arr_ent)
print("*************")
print(plano_arr)

[[ 6 12]
 [30 67]
 [ 9 25]
 [41 72]
 [41 60]
 [90 95]]
*************
[ 6 12 30 67  9 25 41 72 41 60 90 95]


In [15]:
#DHZ 1951
lista_arr = arr_ent.tolist()
lista_arr

[[6, 12], [30, 67], [9, 25], [41, 72], [41, 60], [90, 95]]